version: "3"

services:
  mysql:
    container_name: mysql
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --range_optimizer_max_mem_size=16777216
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ../mysql/sqls/:/docker-entrypoint-initdb.d/
    networks:
      - local-net

  backend:
    container_name: backend
    restart: always
    depends_on:
      - mysql
    volumes:
      - .:/team
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    build: ./
    ports:
      - "8000:8000"
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
