# Generated by Django 4.1 on 2024-01-26 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "completed_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료 날짜"),
                ),
            ],
            options={
                "verbose_name": "하위 업무",
                "verbose_name_plural": "하위 업무",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                (
                    "team_name",
                    models.CharField(max_length=255, unique=True, verbose_name="팀 이름"),
                ),
            ],
            options={
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_name", models.CharField(max_length=255, verbose_name="이름")),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.team",
                        verbose_name="유저-팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "사장님",
                "verbose_name_plural": "사장님",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "completed_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료 날짜"),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.user",
                        verbose_name="업무-유저",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.team",
                        verbose_name="업무-팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "업무",
                "verbose_name_plural": "업무",
            },
        ),
        migrations.CreateModel(
            name="SubTaskTeamAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.subtask",
                        verbose_name="하위업무",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "하위업무-팀-연관정보",
                "verbose_name_plural": "하위업무-팀-연관정보",
            },
        ),
    ]
